### ISSUE TITLE
[FEAT] isHidden should return true, when the panel got destroyed

### ISSUE THREAD

**Issue by lukas-mertens** [roman-rr/cupertino-pane#116]
**What are you trying to add to Cupertino-Pane?**

At the moment, isHidden() returns false on a pane that is destroyed but still referenced from somewhere. This is very unintuitive and it took me 2 hours to figure out, that the close button doesn't hide, but destroys the pane and that a destroyed pane does not count as hidden. I think, the default should be true, because you can't see a destroyed pane.

**Is there an alternative at the latest version?**

[X] Yes (descripe the alternative)
[ ] No

You could do 

```
    const closeBtn = this.drawer['closeEl'] as HTMLElement;
    closeBtn.addEventListener('click', () => {
      this.drawer = null;
    });

```
manually, to track that your Pane got destroyed. This is what I am doing now.

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[X] No

**Comment by sasafister** [comment]
@lukas-mertens can you create PR for this issue? I assume that it will be easier if you test if your solution works, so we can check it out?

**Comment by lukas-mertens** [comment]
When thinking about it, this would be a breaking change, what do you think? As far as I understand, the current code does a hard check for a css-property/position. I assume this is done, to prevent "isHidden" returning true, when the animation is still running. However, I think this is a bit hacky. In my opinion, it would probably be better to manage the state of the panel at one central location, like an enum with the values "visible", "inTransitionToHidden", "inTransitionToDestroyed", "hidden", "destroyed" and so on. This way, you could just do a check on whether or not the state is either "destroyed" or "hidden". And you could probably even expose this information. In the meantime you could document the differences between the "destroyed" and "hidden" state. Because I don't understand exactly, which is for which. Should you always create a new pane, when you want to show the same again? This would make sense, because the close button triggers "destroy", but why is it even possible to hide a pane then? Probably you could also add an option to configure the pane to not be destroyed but hidden, when pressing the closeEl.

**Comment by roman-rr** [comment]
Hello @lukas-mertens thank you for suggestions. 

#### About button destroy/hide
Button close renamed into button destroy to avoid future confusing

#### This is common logic for `isHidden()` method
Pane presented and visible: `isHidden() -> false`
Pane presented and hidden (out of the screen): `isHidden() -> true`
Pane destroyed: `isHidden() -> null`

#### About state handler
- visible/hidden you can check within `isHidden()`
- we have `onDidDismiss` callback, which is emit on destroy, can be used for check `destroyed` state
- we have `onTransitionStart` and `onWillDismiss` callback, can be used for check `inTransitionToHidden`, `inTransitionToDestroyed`
I do not plan to create instance for each state, because it need to be handled manually on every function. I don't sure it is will be so useful, but if this requests will often appears, i will review possibility to make union manual state instance.
