### ISSUE TITLE
[FEAT] Horizontal Module

### ISSUE THREAD

**Issue by davidecampello** [roman-rr/cupertino-pane#164]
**What are you trying to add to Cupertino-Pane?**

Is it possible to open the pane on right (or left or even top) of screen?
Of course if there is a sidemenu the pane sould be opened only with a button, but in some scenario It can be useful to have a sort of sidebar.

**Is there an alternative at the latest version?**

[x] Yes (I think an alternative can be a ion-menu inside the component, but I haven't tried it yet)
[ ] No

**Is this related to an issue?**

[ ] Yes (Give a link to the issue)
[x] No

**Comment by roman-rr** [comment]
@davidecampello Thank you for question. 
Currently available only top and bottom directions. 
I will consider to implement left and right on the next updates cycle.

**Comment by davidecampello** [comment]
Hi @roman-rr! Thank you for the interest and of course for this great project. For this project I used the ion-split-pane as an alternative.
Cheers!

**Comment by roman-rr** [comment]
Hello @davidecampello! It's been a while since i touch this implementation. 
I'm pretty sure that here wouldn't be in plans any type of sidemenu implementation and sidemenu-like maintenance feature.  
We focus here on web3 interfaces, but sidemenu is already deprecated user interface.

But thank you for ideas to make horizontal gestures and in the latest version `v.1.3.0` it was realized. 
I made a demo with horizontal gestures which might be very useful for new type of interfaces. 
It is looks like picture-in-picture but with JS. 
If you will use it in future and will have some feature request, wecome!

[Demo is here](https://output.jsbin.com/dubixep)
![picture-in-picture](https://user-images.githubusercontent.com/10646478/177204784-cefdbcc6-5a37-4320-99f8-64bd7ae8ac8b.gif)

**Comment by davidecampello** [comment]
Hi @roman-rr, really amazing job! Thank you!
