### ISSUE TITLE
[BUG] this.step[...].posY would benefit from null checking

### ISSUE THREAD

**Issue by rgoldiez** [roman-rr/cupertino-pane#177]
I can't pinpoint the exact scenario, but `this.steps` can be an empty array.  Most places in `events.ts` have null checking with typescript's `?` optional chaining operator except this one:

https://github.com/roman-rr/cupertino-pane/blob/5b49dc37dbc33a67093d473053872975dc816ba6/src/events.ts#L252

We've seen a few `Cannot read properties of undefined (reading 'posY')` errors come through our logging framework.  In reading through the code, it seems that the line above can be the only culprit.  It would be good add optional chaining here, too.

**Comment by roman-rr** [comment]
@rgoldiez Thank you for report. 
Always using an optional chaining is a compromise. And here is a good litmus paper to know the exact reason of issue and fix it in correct way. So, decided to fix rather than use additional compromise with chaining. 

Bug is easy to reproduce: just hold `touchmove` action on pane initialization and `touchstart` will be skipped. 

Should be fixed in last commit!

**Comment by rgoldiez** [comment]
@roman-rr - great find and fix!  Thank you!

**Comment by EdithOrt** [comment]
I'm new to this, but how do I download the latest version with this bug fixed?

**Comment by roman-rr** [comment]
Hello @EdithOrt 
You could install package right from git repository. 

```bash
npm install git+https://github.com/roman-rr/cupertino-pane.git
```

**Comment by EdithOrt** [comment]
Thanks @roman-rr , it helped me.
