### ISSUE TITLE
[BUG] Property 'calcFitHeight' does not exist on type 'CupertinoPane'

### ISSUE THREAD

**Issue by modvd** [roman-rr/cupertino-pane#191]
**Describe the bug**
I updated cupertino-pane from 1.2.82 to 1.3.1 and I can't access the calcFitHeight method anymore. Has it been removed ?

**Additional context**
I'm using this project in an Ionic 6 / Angular app.

**Comment by roman-rr** [comment]
@modvd does this property on place `fitHeight: true` ?

Since `1.3.0`, calcFitHeight() method [assigned](https://github.com/roman-rr/cupertino-pane/blob/master/src/modules/fit-height.ts#L25) to instance under **fitHeight** module.  It is required `fitHeight`, as you can see. 

If you don't using `fitHeight`, than you must use `await this.setBreakpoints();` which is public and accessible without modules.

**Comment by modvd** [comment]
Yes my pane has `fitHeight: true`. Do I need to import something new since 1.3.0 ?

**Comment by roman-rr** [comment]
@modvd thank you. Typos was not picked to main instance. Fixed in `1.3.12` and calcFitHeight method also.
